---
title: Interactive web-based Data Visualization and Decision Support Tools
author: Masumbuko Semba
date: '2022-02-03'
slug: []
categories:
  - visualization
tags:
  - Masumbuko Semba
description: ''
thumbnail: ''
---


The gap between scientist and decision makers has existed for decades. Despite the advance of technology in communication, scientists finds difficult to share the information that decision makers can use. Traditional scientific mode of sharing information, which is often depend on peer reviewed articles often fail to plainly communicate results to policy makers and practitioners. Recently, developing tools that support interactive exploration of results have changed the ways scientific evidence findings are communicated in better and easy way. However, the potential for developing interactive graphics into prototypes of decision-support tools that can bridge this communication gap is under appreciated. 

Web applications are useful and  easily accessed by a wide range of users without installing more software. Developing an interactive web applications needed skills in coding with multiple programming languages. These languages included JavaScript, HTML, and CSS. However, Rstudio team lead by Winston Chang developed a Shiny package in R language. The package is a novel because it enables users to create interactive web applications in the R environment. With its ability in data analysis, modeling, and visualization, Shiny  creates decision-support tools in R. 

Shiny is one of the powerful tools in the hand of data analysts and data scientists to develop web-based applications and interactive data visualizations. The Shiny app consists of two important functions: UI and the server function. A key feature of Shiny is the use of reactive programming to automatically update the output when changes are made in the input. Shiny developed by RStudio is a package with the same name. Shiny framework is made up of CSS, HTML, and Java. This gives the freedom to add functionalities to it. 

Among the key advantage of Web-based interactive app is the way they streamline engagement of the users and provide greater transparency in decision making, which can be particularly useful for controversial topics. By promoting greater involvement as well as a shared understanding of trade-offs that are often unavoidable among different scenarios, these decision support tools can help forge a path forward for wicked problems.


The ocean is complex and an effective management need a clear understanding of oceanographic variables and their influence. Unfortunate, a static peer reviewed articles and books, which are often poorly suited to the information needs for effective management schemes are still the dominant mode of communication. Understand the need to share information in digital age, I developed a data driven tool. This interactive decision support tools focus on the coastal and marine environment of Tanzania. The tool present a novel approach of translating a statistical results and model to predict the sea level rise, rising of sea surface temperature and detecting the upwelling events. 

The tool combines the analytical power of the R programming environment with the user-friendly Shiny web interface to create an online platform. This platform help marine scientists and other professionals to explore the dense marine dataset collected from various sources. Some of the sources include ship-based, satellite, drifters and insitu observations. This tool allows users to interact with data and query the system based on the insights the user intends to glean from the tool. You can begin experience the tool functions and services offered at [HERE](https://semba.shinyapps.io/coastal_dashboard/). 


